eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/ #需要将服务注册到那个注册中心（地址）去
server:
  port: 7777
spring:
  application:
    name: demo-provider
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aBreaking/spring-cloud-demo/
          search-paths: config-repo
          username: aBreaking
          password: lv5172551
