eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/ #将服务注册到那个注册中心去
server:
  port: 7777
spring:
  application:
    name: demo-provider
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aBreaking/spring-cloud-demo/  #github 仓库地址
          search-paths: config-repo #配置中心
          username: aBreaking
          password: lv5172551
